# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

infer_labels <- function(DTM, ndocs, nunique, ntokens, nelem, T, niter, BETA, ALPHA, PCW) {
    .Call('_superlda_infer_labels', PACKAGE = 'superlda', DTM, ndocs, nunique, ntokens, nelem, T, niter, BETA, ALPHA, PCW)
}

infer_topics <- function(DTM, ndocs, nunique, ntokens, nelem, T, niter, BETA, ALPHA, PCW) {
    .Call('_superlda_infer_topics', PACKAGE = 'superlda', DTM, ndocs, nunique, ntokens, nelem, T, niter, BETA, ALPHA, PCW)
}

train_label_word <- function(DTM, DLM, ndocs, nunique, ntokens, nelem, niter, BETA, ALPHA) {
    .Call('_superlda_train_label_word', PACKAGE = 'superlda', DTM, DLM, ndocs, nunique, ntokens, nelem, niter, BETA, ALPHA)
}

